### ISSUE TITLE
Default build platform on Ubuntu

### ISSUE THREAD

**Issue by EmilieSD** [jserot/rfsm-light#2]
Default build platform on Ubuntu does not seem to correspond to the help menu indications.

-----------------------
Ubuntu version 18.04.5

    ./configure --help 

    Usage: configure [options]  
    Options: [defaults in brackets after descriptions]
      --platform NAME         target platform (linux, macos or windows) [default: linux]
      [...]
      --help                  print this message

```
./configure

** Configuration summary **

Directory where the distribution will be installed:
        binaries................   /usr/local/rfsm-light/bin
        library.................   /usr/local/rfsm-light/lib
        documentation............. /usr/local/rfsm-light/doc

** Wrote file ./config
** Wrote file ./platform
** Configuration completed successfully **`
```

```
make

make: Nothing to be done for 'all'.
```

```
make install

make: Nothing to be done for 'install'.
```

```
./configure --platform linux

** Configuration summary **

Directory where the distribution will be installed:
        binaries................   /usr/local/rfsm-light/bin
        library.................   /usr/local/rfsm-light/lib
        documentation............. /usr/local/rfsm-light/doc

** Wrote file ./config
** Wrote file ./platform
** Configuration completed successfully **
```

`make` --> Starts build

**Comment by jserot** [comment]
Fixed in current source tree.
The default name for the platform when building on Linux is now correctly set to "linux" by configure.
Thx for reporting
